title: The Seventh Art Club CNH
cpright: "SAC 2016"
url: "http://thesac.github.io"
relative_permalinks: false
permalink: /404.html
markdown: kramdown
highlighter: rouge
cover: "http://thesac.github.io/img/big_logo.jpg"
